# Generated by Django 5.1.3 on 2025-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome Email"),
                            ("PROMO", "Promotional Email"),
                            ("FOLLOW_UP", "Follow-up Email"),
                            ("RE_ENGAGE", "Re-engagement Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("html_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromotionalOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LOAN", "Loans"),
                            ("INS", "Insurance"),
                            ("CC", "Credit Cards"),
                            ("GEN", "General"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("promo_code", models.CharField(blank=True, max_length=50, null=True)),
                ("expiration", models.DateField()),
                ("target_criteria", models.JSONField(default=dict)),
                ("priority", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offer_images/"),
                ),
            ],
        ),
    ]
