# Generated by Django 5.1.3 on 2025-07-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="campaign",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="examples",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="must_include",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="tone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="promotionaloffer",
            name="campaign",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
