# Generated by Django 5.1.3 on 2025-07-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="finance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="shopping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="technology",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="travel",
            field=models.BooleanField(default=False),
        ),
    ]
