# Generated by Django 5.1.3 on 2025-07-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_default_preferences"),
        ("users", "0006_userpreferences_finance_userpreferences_shopping_and_more"),
    ]

    operations = []
