# Generated by Django 5.1.3 on 2025-07-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_emailtemplate_campaign_emailtemplate_examples_and_more"),
        ("users", "0007_merge_20250720_1943"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailinteraction",
            name="clicked_links",
        ),
        migrations.RemoveField(
            model_name="emailinteraction",
            name="opened_count",
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.promotionaloffer",
            ),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="email_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="emailinteraction",
            index=models.Index(
                fields=["sent_at", "opened_at"], name="users_email_sent_at_63a5a3_idx"
            ),
        ),
    ]
