# Generated by Django 5.1.3 on 2025-07-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_emailtemplate_campaign_emailtemplate_examples_and_more"),
        ("users", "0008_remove_emailinteraction_clicked_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailinteraction",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                help_text="Which promo offer (if any) this interaction relates to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.promotionaloffer",
            ),
        ),
    ]
