# Generated by Django 5.1.3 on 2025-07-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_emailtemplate_campaign_emailtemplate_examples_and_more"),
        ("users", "0009_alter_emailinteraction_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinteraction",
            name="clicked_links",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="opened_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="email_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.promotionaloffer",
            ),
        ),
    ]
