# Generated by Django 5.1.3 on 2025-07-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_emailinteraction_clicked_links_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailinteraction",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.RemoveIndex(
            model_name="emailinteraction",
            name="users_email_sent_at_63a5a3_idx",
        ),
        migrations.RemoveField(
            model_name="emailinteraction",
            name="offer",
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="follow_up_sent",
            field=models.BooleanField(
                default=False,
                help_text="True once a follow-up has been sent for this interaction",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email_open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="clicked_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("PROMO", "Promotional"),
                    ("WELCOME", "Welcome"),
                    ("FOLLOW_UP", "Follow-Up"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="opened_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
