# Generated by Django 5.1.3 on 2025-07-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_emailinteraction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailinteraction",
            name="follow_up_sent",
            field=models.BooleanField(default=False),
        ),
    ]
