# Generated by Django 5.1.3 on 2025-07-24 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_emailinteraction_follow_up_sent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailinteraction",
            options={},
        ),
        migrations.RemoveField(
            model_name="emailinteraction",
            name="follow_up_sent",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email_open_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="clicked_links",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="email_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="opened_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
