# Generated by Django 5.1.3 on 2025-07-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_emailinteraction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinteraction",
            name="follow_up_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="follow_up_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="original_interaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_ups",
                to="users.emailinteraction",
            ),
        ),
    ]
