# Generated by Django 5.1.3 on 2025-07-31 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_emailinteraction_follow_up_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailinteraction",
            name="clicked_links",
        ),
        migrations.RemoveField(
            model_name="emailinteraction",
            name="opened_count",
        ),
        migrations.AddField(
            model_name="emailinteraction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
